### ISSUE TITLE
Errors while running simulation

### ISSUE THREAD

**Issue by guido-s** [rritaz/RVE-Meta-analysis-SMD#1]
Hi,

I tried to run the simulations with a reduced number of iterations. However, I encountered the following problems / errors.

First, the change in file names from df_HR2.R and df_HR3.R to df-HR2.R and df-HR3.R (https://github.com/rritaz/RVE-Meta-analysis-SMD/commit/edb52822e20bb80c4c594f18c9a21d55b8e98da4) was forgotten in the files sims.R and simulation-setup.txt.

Second, after changing the file names and running the simulations with 100 iterations, I got the following error:

```
> df_sims <- data.frame()
> for (l in 1:100){
+     currentResults <- main()
+     df_sims <- rbind(df_sims, currentResults)
+ }
Error in if (toReturn < 0) { : missing value where TRUE/FALSE needed
Calls: main -> tauHat_DL
In addition: There were 20 warnings (use warnings() to see them)
Execution halted
```

The mentioned warnings are the following

```
Warning messages:
1: In rnorm(1, delta, sqrt(tau_sq)) : NAs produced
2: In rnorm(1, delta, sqrt(tau_sq)) : NAs produced
...
11: In rnorm(1, delta, sqrt(var_cohenD(n))) : NAs produced
...
20: In rnorm(1, delta, sqrt(var_cohenD(n))) : NAs produced
```

I am not sure how to tackle this error.

Best,
Guido

P.S. I am running R, version 4.3.1 under macOS.

**Comment by rritaz** [comment]
Hi,

The kValue inside the main function has to be manually changed, and corresponds to the number of rows in the n_values file. So for example, if you set kValue = 2, and your first column of the n_values file, cell A1=100, cell A2=100, you should not get these errors. If you set kValue = 10, then the first column of the n_values file would contain a vector of 100s of length 10. 

Please let me know if there are additional problems, or if the logic of the simulations should be made clearer in the text file I included in my GitHub repository. 

Thank you,
Rrita

**Comment by guido-s** [comment]
Thank you for the clarification. I made a couple of changes which in my view would increase the readability and flexibility of the simulation code (see pull request).

Best,
Guido

**Comment by rritaz** [comment]
Thank you!
